version: "3"
services:

  gitea:
    image: gitea/gitea:latest
    restart: always
    ports:
      - "13000:3000"
      - "10022:22"
    networks:
      giteanet:
    hostname: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    volumes:
      - /docker_data/gitea:/data
    depends_on:
      - mariadb

  mariadb:
    image: mariadb-replicas:1.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MARIADB_REPLICATION_SERVER_TYPE=MASTER
      - MARIADB_REPLICATION_USER=replicator
      - MARIADB_REPLICATION_PASSWORD=replicatorpwd
    networks:
      giteanet:
      dbnet:
    hostname: mariadb
    volumes:
      - /docker_data/mariadb_master:/var/lib/mysql

  mariadb-slave:
    image: mariadb-replicas:1.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MARIADB_REPLICATION_SERVER_TYPE=SLAVE
      - MARIADB_REPLICATION_USER=replicator
      - MARIADB_REPLICATION_PASSWORD=replicatorpwd
      - MARIADB_REPLICATION_HOST=mariadb-master
      - MARIADB_REPLICATION_SERVER_ID=1001
    networks:
      dbnet:
    hostname: mariadb-sl4ve
    volumes:
      - /docker_data/mariadb_slave:/var/lib/mysql
    depends_on:
      - mariadb

networks:
  giteanet:
  dbnet:
